[package]
name = "in_code_learning_rust"
version = "0.1.0"
authors = ["Jesse Zhuang <zhzexi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.6"
typename = "0.1.1"
